importScripts('https://cdnjs.cloudflare.com/ajax/libs/seedrandom/3.0.1/seedrandom.min.js')
importScripts('https://cdnjs.cloudflare.com/ajax/libs/sjcl/1.0.8/sjcl.min.js')
importScripts("constants.js")
importScripts("fields.js")
importScripts("util.js")
importScripts("presets/safe.js")

const VER_ERROR = 'Seed generated by a different version of the randomizer.'

self.addEventListener('message', function(message) {
  try {
    const data = message.data
    const fileData = data.fileData
    const array = new Uint8Array(fileData)
    const check = new adRando.util.checked(array)
    Math.seedrandom(adRando.util.saltSeed(
      data.version,
      data.options,
      data.seed,
    ))
    const options = self.adRando.util.Preset.options(data.options)
    let hex = adRando.util.setSeedAzureDreams(check, options, data.seed, data.userSeed)
    adRando.util.setAppliedOptions(options, check, hex)
    const checksum = check.sum()
    if (data.checksum && data.checksum !== checksum) {
      throw new Error(VER_ERROR)
    }
    self.postMessage({
      seed: data.seed,
      data: fileData,
      checksum: checksum,
      info: data.info,
      userSeed: data.userSeed,
    }, [fileData])
  } catch (e) {
    self.postMessage({error: e.message})
  }
})
